version: '3.8'

services:
  rustdesk-server:
    image: rustdesk/rustdesk-server:latest
    container_name: rustdesk-server
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - RUST_LOG=${LOG_LEVEL:-info}
      - DB_URL=${DB_URL:-sqlite:///data/db_v2.sqlite3}
      - KEY=${KEY_FILE:-/data/id_ed25519}
    ports:
      - "${TCP_PORT:-21116}:21116"  # ID Server TCP
      - "${UDP_PORT:-21117}:21117/udp"  # Relay Server UDP
      - "${WEB_PORT:-21118}:21118"  # Web Server
    volumes:
      - rustdesk_data:/data
      - ./reverse-proxy/certs:/certs:ro
    networks:
      - rustdesk-network
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    container_name: rustdesk-nginx
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./reverse-proxy/certs:/etc/nginx/certs:ro
      - ./reverse-proxy/html:/usr/share/nginx/html:ro
    networks:
      - rustdesk-network
    environment:
      - DOMAIN=${DOMAIN:-localhost}

volumes:
  rustdesk_data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind

networks:
  rustdesk-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
